version: '3'

services:

  db:
    image: "postgres:9.6-alpine"
    container_name: db
    restart: always

    ports:
      - 5433:5433

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=studentDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata


  flamup:
    build: ./
    container_name: flamup
    environment:
      - DB_SERVER:db
      - POSTGRES_DB=studentDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 8081:8081 # Forward the exposed port 8080 on the container to port 8080 on the host machine

    depends_on:
      - db

volumes:
  postgres_data: