version: '2'
services:
  backend:
    container_name: emt_backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: emt_backend:latest
    depends_on:
      - db
    ports:
      - 9090:9090

  frontend:
    container_name: emt_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: emt_frontend:latest
    depends_on:
      - backend
    ports:
      - 3000:80

  db:
    container_name: emt_db
    image: postgres
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=student
